namespace: nerc
name: netbox
version: '0.0.1'
readme: README.md
authors:
  - aabaris
description: Collection of roles to deploy Netbox services
repository: https://github.com/nerc-project/nerc-netbox-ansible-collection
